[package]
name = "quarter_month"
version = "0.1.0"
authors = ["Muhammad Dony Mulya <55097092+ExLog@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
